config/routes.rb
Rails.application.routes.draw do
  resources :daily_attachments
  resources :daily_comments
  # resources :diaries
  # resources :dailies, except: [:index]
  # get '/diaries/:id/dailies', to: 'dailies#index', as: 'diary_dailies'
  
  resources :diaries, except: [:show] do
    resources :dailies
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'diary/community', to: 'diaries#show'
  get 'diary/mydiary'
  post 'diaries/:id/like' => 'likes#like_toggle', as: 'like'
  get '/about', to: 'home#about'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daily_attachment.rb
class DailyAttachment < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :daily
    


end

app/controllers/daily_attachments_controller.rb
class DailyAttachmentsController < ApplicationController
  before_action :set_daily_attachment, only: [:show, :edit, :update, :destroy]

  # GET /daily_attachments
  # GET /daily_attachments.json
  def index
    @daily_attachments = DailyAttachment.all
  end

  # GET /daily_attachments/1
  # GET /daily_attachments/1.json
  def show
  end

  # GET /daily_attachments/new
  def new
    @daily_attachment = DailyAttachment.new
  end

  # GET /daily_attachments/1/edit
  def edit
  end

  # POST /daily_attachments
  # POST /daily_attachments.json
  def create
    @daily_attachment = DailyAttachment.new(daily_attachment_params)

    respond_to do |format|
      if @daily_attachment.save
        format.html { redirect_to @daily_attachment, notice: 'Daily attachment was successfully created.' }
        format.json { render :show, status: :created, location: @daily_attachment }
      else
        format.html { render :new }
        format.json { render json: @daily_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_attachments/1
  # PATCH/PUT /daily_attachments/1.json
  def update
    respond_to do |format|
      if @daily_attachment.update(daily_attachment_params)
        format.html { redirect_to @daily_attachment.daily, notice: 'Daily attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_attachment }
      end
    end
  end

  # DELETE /daily_attachments/1
  # DELETE /daily_attachments/1.json
  def destroy
    @daily_attachment.destroy
    respond_to do |format|
      format.html { redirect_to daily_attachments_url, notice: 'Daily attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_attachment
      @daily_attachment = DailyAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_attachment_params
      params.require(:daily_attachment).permit(:daily_id, :avatar)
    end
end

app/helpers/daily_attachments_helper.rb
module DailyAttachmentsHelper
end

app/views/daily_attachments/_form.html.erb
<%= image_tag @daily_attachment.avatar %>
<%= form_for(@daily_attachment) do |f| %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_attachments/edit.html.erb
<h1>Editing Daily Attachment</h1>

<%= render 'form', daily_attachment: @daily_attachment %>

<%= link_to 'Show', @daily_attachment %> |
<%= link_to 'Back', daily_attachments_path %>

app/views/daily_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Daily</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_attachments.each do |daily_attachment| %>
      <tr>
        <td><%= daily_attachment.daily_id %></td>
        <td><%= daily_attachment.avatar %></td>
        <td><%= link_to 'Show', daily_attachment %></td>
        <td><%= link_to 'Edit', edit_daily_attachment_path(daily_attachment) %></td>
        <td><%= link_to 'Destroy', daily_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Attachment', new_daily_attachment_path %>

app/views/daily_attachments/new.html.erb
<h1>New Daily Attachment</h1>

<%= render 'form', daily_attachment: @daily_attachment %>

<%= link_to 'Back', daily_attachments_path %>

app/views/daily_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Daily:</strong>
  <%= @daily_attachment.daily_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @daily_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_daily_attachment_path(@daily_attachment) %> |
<%= link_to 'Back', daily_attachments_path %>