config/routes.rb
Rails.application.routes.draw do
  resources :daily_attachments
  resources :daily_comments
  # resources :diaries
  # resources :dailies, except: [:index]
  # get '/diaries/:id/dailies', to: 'dailies#index', as: 'diary_dailies'
  
  resources :diaries, except: [:show] do
    resources :dailies
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'diary/community', to: 'diaries#show'
  get 'diary/mydiary'
  post 'diaries/:id/like' => 'likes#like_toggle', as: 'like'
  get '/about', to: 'home#about'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/diary.rb
class Diary < ApplicationRecord
    mount_uploader :profile_img, AvatarUploader
    belongs_to :user
    has_many :dailies
    has_many :likes
    has_many :liking_users, through: :likes, source: :user
    
    validates :title, presence: true, length: { minimum: 2, maximum: 20 }
    validates :content, presence: true, length: { minimum: 2, maximum: 50 }
    validates :budget, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :start_city, presence: true
    validates :end_city, presence: true
    validates :country_count, presence: true
    validates :profile_img, presence: true
    
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_diary, only: [:edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
    
    # if Like.find_by(user: current_user, diary: @diary).nil?
    #   @button = '좋아요'
    # else
    #   @button = '좋아요 취소'
    # end
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
    @diaries = Diary.all
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)
    
    respond_to do |format|
      if @diary.save
        format.html { redirect_to diaries_url, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:start_date, :end_date, :title, :content, :budget, :start_city, :end_city, :country_count, :eurail, :secret, :profile_img, :user_id)
    end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_helper.rb
module DiaryHelper
end

app/views/diaries/_card.html.erb
<div class="col-lg-6 col-sm-6">
  		<article class="blog-post" data-id="<%=diary.id%>">
  			<div class="featured-post">
  				<%= link_to image_tag(diary.profile_img) , diary_dailies_path(diary.id) %>
  			</div><!-- /.featured-post -->
  			<div class="content-post">
  				<div class="entry-post">
  					<ul class="entry-meta">
  						<li class="date">
  							<%= diary.updated_at %>
  						</li>
  					</ul>
  					<h2 class="entry-title">
  						<%= diary.title %>
  					</h2>
  				</div>
  				<p>
  					<%= diary.content %>
  				</p>
  				<%= diary.likes.count %>
  				<% if diary.liking_users.include? current_user %>
  				    <%= link_to "좋아요 취소", like_path(diary), method: :POST %>
  				<% else %>
  				    <%= link_to "좋아요", like_path(diary), method: :POST %>
  				<% end %>
  			</div><!-- /.content-post -->
  		</article><!-- /.blog-post -->
  		
</div><!-- /.col-lg-3 col-sm-6 -->

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="container">
	<div class="row">
		<div class="col-md-12">
		  
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field"> 
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :diary_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :diary_end_date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :diary_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :diary_content %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.number_field :budget, id: :diary_budget %>
  </div>

  <div class="field">
    <%= form.label :start_city %>
    <%= form.text_field :start_city, id: :diary_start_city %>
  </div>

  <div class="field">
    <%= form.label :end_city %>
    <%= form.text_field :end_city, id: :diary_end_city %>
  </div>

  <div class="field">
    <%= form.label :country_count %>
    <%= form.number_field :country_count, id: :diary_country_count %>
  </div>

  <div class="field">
    <%= form.label :eurail %>
    <%= form.check_box :eurail, id: :diary_eurail %>
  </div>
  
  <div class="field">
    <%= form.label :secret %>
    <%= form.check_box :secret, id: :diary_secret %>
  </div>
  
  <div class="field">
      <%= form.file_field :profile_img, accept: 'image/jpeg, image/gif, image/png' %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
  
  </div>
  </div>
  </div>
<% end %>

app/views/diaries/_post.html.erb
<!-- Single Popular Course -->
<div class="col-12 col-md-6 col-lg-4">
    <div class="single-popular-course mb-100 wow fadeInUp" data-wow-delay="250ms">
        <img src= "<%= diary.profile_img %>" alt="">
        <!-- Course Content -->
        <div class="course-content">
            <div class="meta d-flex align-items-center", style="color:#A6A6A6;">
                기간 : <%= diary.start_date.month%>월 <%= diary.start_date.day%>일 ~ <%= diary.end_date.month%>월 <%= diary.end_date.day%>일 
                <br>인아웃 : <%= diary.start_city%> - <%= diary.end_city%>
                <br>여행 한 국가 : <%= diary.country_count %> 개국
                <br>총 예산 : <%= diary.budget %> 원
                <% if diary.eurail %>
                    <br>유레일 : 사용 
                <% else %>
                    <br>유레일 : 미사용
                <% end %>
                
            </div>
            <span class="diary_title"><%= diary.title %></span>
            </br><br>
            <p><%= diary.content %></p>
        </div>
        <!-- Seat Rating Fee -->
        <div class="seat-rating-fee d-flex justify-content-between">
            <div class="seat-rating h-100 d-flex align-items-center">
                <div class="seat">
                   <span><%= diary.likes.count %></span>
                    <% if diary.liking_users.include? current_user %>
  				        <%= link_to "좋아요 취소", like_path(diary), method: :POST, remote: true %>
          			<% else %>
          				<%= link_to "좋아요", like_path(diary), method: :POST, remote: true %>
          			<% end %>
                </div>
                <div class="rating">
                    <%= diary.user.email.split('@')[0] %>
                </div>
                <div class="seat">
                    <% if diary.secret %>
                        숨김
                    <% end %>
                </div>
            </div>
            <div class="course-fee h-100">
                <%= link_to 'Go', diary_dailies_path(diary) %>
            </div>
        </div>
    </div>
</div>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<div class="single-slider-4 slider-height-daily bg-img" style="background-image: url(<%=asset_path 'core-img/paris-2017-home.jpg' %>)">
	<div class="container">
		<!--<div class="breadcrumb-content text-center">-->
			<div class="row">
			    <div class="reviewer">
	  				<div class="reviewer-image">
	  					<img src= "<%= current_user.profile_img %>">
	  				</div><!-- /.reviewer-image -->
	  				<div class="reviewer-info">
	  					<h5 class="name"><%= current_user.email %></h5>
	  					<span>Traveler</span>
	  					<ul class="social-re">
	  						<li>
	  							<a href="#" title="">
	  								<i class="ti-facebook" aria-hidden="true"></i>
	  							</a>
	  						</li>
	  						<li>
	  							<a href="#" title="">
	  								<i class="ti-twitter-alt" aria-hidden="true"></i>
	  							</a>
	  						</li>
	  						<li>
	  							<a href="#" title="">
	  								<i class="ti-instagram" aria-hidden="true"></i>
	  							</a>
	  						</li>
	  						<li>
	  							<a href="#" title="">
	  								<i class="ti-google" aria-hidden="true"></i>
	  							</a>
	  						</li>
	  						<li>
	  							<a href="#" title="">
	  								<i class="ti-pinterest" aria-hidden="true"></i>
	  							</a>
	  						</li>
	  					</ul>
	  				</div><!-- /.reviewer-info -->
	  			</div><!-- /.reviewer -->
	  			<div class="plus_button">
	  				<h2 style="color:white;"><%=link_to '+ Plus Diary', new_diary_path %></h2>
	  			</div>
  			</div>
		<!--</div>-->
	</div>
</div>


<section class="flat-row flat-main-blog">
	<div class="container" >
	  <div class="row">
  		
  		<div class="height50"></div>
  		
  		
  		<div class="row col-lg-9">
			<section class="flat-row flat-main-blog", style="padding:0px;">
				<div class="container" >
				  <div class="row">
			  		<!--<section class="popular-courses-area section-padding-100-0" >-->
					    <div class="container">
					        <div class="row">
					            <% @diaries.each do |diary| %>
					  				<% if current_user.id == diary.user_id %> <!-- current_user 라면 -->
								    	<%= render 'post', diary: diary %><!-- 다이어리 섹션 -->
								    <% end %>
								<% end %>
					        </div>
					    </div>
					<!--</section>-->
					</div><!-- /.row -->
					
					<div class="height50"></div>
				</div><!-- /.container -->
			</section><!-- /.flat-main-blog -->
  			
  		</div>
		</div><!-- /.row -->
		
		<div class="height50"></div>
	</div><!-- /.container -->
</section><!-- /.flat-main-blog -->

<%= render 'shared/modal1' %>
<%= render 'shared/modal2' %>
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>

<script>
    $(".blog-post").mouseover(function(){
    	var id = $(this).data('id');
        $(`.diary_info[data-id=${id}]`).show();
    });
    
    $(".blog-post").mouseout(function(){
      	var id = $(this).data('id');
        $(`.diary_info[data-id=${id}]`).hide();
    });
</script>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<div class = "diary_form">
    <%= render 'form', diary: @diary %>
    <%= link_to 'Back', diaries_path %>
</div>

app/views/diaries/show.html.erb
<div class="single-slider-4 slider-height-daily bg-img" style="background-image: url(<%=asset_path 'core-img/comm1.png' %>)">
	<div class="container">
		<div class="breadcrumb-content text-center">
			    <h2>Community</h2>
		</div>
	</div>
</div>


<section class="flat-row flat-main-blog">
	<div class="container" >
	  <div class="row">
			    <div class="col-12">
                <div class="section-title text-center mb-60">
                    <h3>모두의 Diary</h3>
                </div>
            </div>
    <div class="container">
        <div class="row">
            <!-- render 시키는 곳 -->
            <% @diaries.each do |diary| %>
              <% if !diary.secret %>
                <%= render 'post', diary: diary %>
              <% end %>
            <% end %>
        </div>
    </div>
		</section>
		</div><!-- /.row -->
		
		<div class="height50"></div>
	</div><!-- /.container -->
</section><!-- /.flat-main-blog -->

<%= render 'shared/modal1' %>
<%= render 'shared/modal2' %>
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>