config/routes.rb
Rails.application.routes.draw do
  resources :daily_attachments
  resources :daily_comments
  # resources :diaries
  # resources :dailies, except: [:index]
  # get '/diaries/:id/dailies', to: 'dailies#index', as: 'diary_dailies'
  
  resources :diaries, except: [:show] do
    resources :dailies
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'diary/community', to: 'diaries#show'
  get 'diary/mydiary'
  post 'diaries/:id/like' => 'likes#like_toggle', as: 'like'
  get '/about', to: 'home#about'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daily_comment.rb
class DailyComment < ApplicationRecord
    belongs_to :user
    belongs_to :daily
end

app/controllers/daily_comments_controller.rb
class DailyCommentsController < ApplicationController
  before_action :set_daily_comment, only: [:show, :edit, :update, :destroy]

  # GET /daily_comments
  # GET /daily_comments.json
  def index
    @daily_comments = DailyComment.all
  end

  # GET /daily_comments/1
  # GET /daily_comments/1.json
  def show
    @daily_comment = DailyComment.find(params[:id])
    @daily_comments = DailyComment.all
  end
  
  def new
    @daily_comment = DailyComment.new
  end

  # GET /daily_comments/1/edit
  def edit
    @daily_comment = DailyComment.find(params[:id])
  end

  # POST /daily_comments
  # POST /daily_comments.json
  def create
    @daily_comment = DailyComment.new(daily_comment_params)
    # debugger
    respond_to do |format|
      if @daily_comment.save
        format.html {redirect_back(fallback_location: root_path)}
        format.js {}
        format.json {render 'new_daily_comment'}

      else
        redirect_to new_daily_comment_url(@daily_comment)
      end
    end
  end
  
  # PATCH/PUT /daily_comments/1
  # PATCH/PUT /daily_comments/1.json
  def update
    @daily_comment = DailyComment.find(params[:id])
    
    if @daily_comment.update(daily_comment_params)
      respond_to do |format|
        format.html { redirect_to diary_daily_url(@daily_comment.diary_id, @daily_comment.daily), notice: 'Daily comment was successfully updated.' }
        format.js
      end
    else
        redirect_back(fallback_location: root_path)
    end
  end
  
  # DELETE /daily_comments/1
  # DELETE /daily_comments/1.json
  def destroy
    
    @daily_comment.destroy
    respond_to do |format|
      format.html { redirect_to daily_comments_url, notice: 'Daily comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_comment
      @daily_comment = DailyComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_comment_params
      params.require(:daily_comment).permit(:content, :daily_id, :diary_id, :user_id)
    end
    

end

app/helpers/daily_comments_helper.rb
module DailyCommentsHelper
end

app/views/daily_comments/_comment.html.erb
<p id="notice"><%= notice %></p>

<div class="single-blog-replay">
  <div class="comment_person">
  </div>
  <div class="replay-info-wrapper">
      <div class="replay-info">
          <div class="replay-name-date">
              <h6><%= comment.user.email %></a></h6>
              <span><%= comment.created_at %></span>
          </div>
          <div class="replay-btn">
              <%= link_to('수정', edit_daily_comment_path(comment), remote: true) %>
              <%= link_to('삭제', daily_comment_path(comment), method: :delete, remote: true) %>
          </div>
      </div>
      <p><%= comment.content %></p>
  </div>
</div>

app/views/daily_comments/_form.html.erb
<%= form_with(model: daily_comment, local: true, remote: true, html: {style: "display: inline"}) do |form| %>
  

<div class="single-blog-replay">
  <div class="replay-info-wrapper">
      <div class="replay-info">
        <div class="field">
         <%= form.text_field :content, id: :daily_comment_content %>
          <div class="replay-btn">
              <%= form.submit %>
              </div>
          </div>
      </div>
  </div>
</div>

<% end %>

app/views/daily_comments/create.js.erb
var comments = $('ul#daily_comments');
var new_comment = "<%= escape_javascript(render 'comment', comment: @daily_comment) %>";
comments.append(new_comment);

app/views/daily_comments/destroy.js.erb
$("a[href='/daily_comments/<%=params[:id]%>']").parent().parent().remove();

app/views/daily_comments/edit.html.erb
<h1>Editing Daily Comment</h1>

<%= render 'form', daily_comment: @daily_comment %>

<%= link_to 'Show', @daily_comment %> |
<%= link_to 'Back', daily_comments_path %>

app/views/daily_comments/edit.js.erb
if(form.length != 0) {
    form.remove();
    content.show();
}

content = $("a[href='/daily_comments/<%=params[:id]%>/edit']").parent().parent().next();
form_temp = "<%= j(render 'form', daily_comment: @daily_comment)%>";
content.hide();
content.before(form_temp);
form = content.prev();

app/views/daily_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_comments.each do |daily_comment| %>
      <tr>
        <td><%= daily_comment.content %></td>
        <td><%= link_to 'Show', daily_comment %></td>
        <td><%= link_to 'Edit', edit_daily_comment_path(daily_comment) %></td>
        <td><%= link_to 'Destroy', daily_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Comment', new_daily_comment_path %>

app/views/daily_comments/new.html.erb
<h1>New Daily Comment</h1>

<%= render 'form', daily_comment: @daily_comment %>

<%= link_to 'Back', daily_comments_path %>