config/routes.rb
Rails.application.routes.draw do
  resources :daily_attachments
  resources :daily_comments
  # resources :diaries
  # resources :dailies, except: [:index]
  # get '/diaries/:id/dailies', to: 'dailies#index', as: 'diary_dailies'
  
  resources :diaries, except: [:show] do
    resources :dailies
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  
  get 'diary/community', to: 'diaries#show'
  get 'diary/mydiary'
  post 'diaries/:id/like' => 'likes#like_toggle', as: 'like'
  get '/about', to: 'home#about'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daily.rb
class Daily < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :diary, optional: true
    has_many :daily_attachments
    accepts_nested_attributes_for :daily_attachments
    
    has_many  :daily_comments
    
    validates :title, presence: true, length: { minimum: 2, maximum: 100 }
    validates :content, presence: true, length: { minimum: 2 }
  
  

end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :set_daily, only: [:indx, :show, :edit, :update, :destroy]
  
  # GET /dailies
  # GET /dailies.json
  # daily 작성한 것 목록 보여주는 화면
  def index
    @diary = Diary.find params[:diary_id]
    @dailies = @diary.dailies
    
 if Like.find_by(user: current_user, diary: @diary).nil?
      @button = '좋아요'
    else
      @button = '좋아요 취소'
    end  end

  # GET /dailies/1
  # GET /dailies/1.json
  def show
    # daily 누르면 보여주는 화면임
    @diary = Diary.find params[:diary_id]
    @daily_comment = DailyComment.new
    @daily_comments = @daily.daily_comments
    @daily_attachments = @daily.daily_attachments.all
    # @daily_attachments = DailyAttachment.find(@daily)
    
  end

  # GET /dailies/new
  # daily 입력 받아오기 !
  def new
    @diary = Diary.find params[:diary_id]
    @daily = Daily.new
    @daily_attachment = @daily.daily_attachments.build
  end

  # GET /dailies/1/edit
  def edit
    # daily 수정입력
  end

  # POST /dailies
  # POST /dailies.json
  # daily 를 저장합니당 
  def create
    #daily_params = params.require(:daily).permit(:title, :today, :content, :country)
    @daily = Daily.new(daily_params)
    # debugger
    if @daily.save
      params[:daily_attachments]['avatar'].each do |a|
          @daily_attachment = @daily.daily_attachments.create!(:avatar => a)
      end
      redirect_to diary_daily_url(@daily.diary, @daily)
    else
      redirect_to new_diary_daily_url(params[:diary_id])
    end
  end

  # PATCH/PUT /dailies/1
  # PATCH/PUT /dailies/1.json
  def update
    # daily 수정해서 저장해
    #daily_params = params.require(:daily).permit(:title, :today, :content, :country)
    
    if @daily.update(daily_params)
      redirect_to daily_url(@daily)
    else 
      redirect_to edit_daily_url(@daily)
    end
  end

  # DELETE /dailies/1
  # DELETE /dailies/1.json
  def destroy
    @daily.destroy
    respond_to do |format|
      format.html { redirect_to diary_dailies_url, notice: 'Daily was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @daily = Daily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_params
      params.require(:daily).permit(:title, :today, :content, :country, :user_id, :diary_id, daily_attachments_attributes: [:id, :daily_id, :avatar])
    end
    
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/views/dailies/_form.html.erb
<%= form_with(model: daily, url: [diary, daily], local: true, html: { multipart: true }) do |form| %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :diary_id, value: diary.id %>

  <% if daily.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily.errors.count, "error") %> prohibited this daily from being saved:</h2>

      <ul>
      <% daily.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="container">	
					<div class="col-md-12">
					  <div id="owl-project-wrapper">
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, id: :daily_title %>
            </div>
          
            <div class="field">
              <%= form.label :today %>
              <%= form.date_select :today, id: :daily_today %>
            </div>
          
            <div class="field">
              <%= form.label :content,'내용' %>
              <%= form.text_area :content, id: :daily_content,class: "tinymce", cols: 20, rows: 10 %>
              <%= tinymce %>
            </div>
            
            <%= form.fields_for :daily_attachments do |p| %>
               <div class="field">
                 <%= p.label :avatar %><br>
                 <%= p.file_field :avatar, :multiple => true, name: "daily_attachments[avatar][]" %>
               </div>
            <% end %>
            
            
            <div class="field">
              <%= form.label :country %>
              <%= form.text_field :country, id: :daily_country %>
            </div>
          
            <div class="actions">
              <%= form.submit %>
            </div>
  </div>
  </div>
  </div>
<% end %>

app/views/dailies/edit.html.erb
<h1>Editing Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Show', @daily %> |
<%= link_to 'Back', dailies_path %> |

app/views/dailies/index.html.erb
<div class="single-slider-4 slider-height-daily bg-img" style="background-image: url(<%=asset_path 'core-img/plan2.jpg' %>)">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <h2>My Diary</h2>
            <ul>
                <li><h3 style="color:white; font-weight:bold;"><%= @diary.title %></h3></li>
            </ul>
        </div>
    </div>
</div>
<div class="section section-padding-top-bottom white-background">
	<div class="container">			
		<div class="sixteen columns">
			<div id="blog-filter">
				<ul id="filter">
					<li><a href="#" class="current" data-filter="*" title="">all</a></li>
					<li><a href="#" data-filter=".photo" title="">photo</a></li>
					<li><a href="#" data-filter=".gallery" title="">gallery</a></li>
					<li><a href="#" data-filter=".video" title="">video</a></li>
					<li><a href="#" data-filter=".quote" title="">quote</a></li>
				</ul>
			</div>
		</div>	
	</div>
	
	<div class="clear"></div>	

	<div id="blog-grid">
		
	<div class="blog-box-1 grey-background photo">
			<div class="date"><p>새로운 일기를 작성하려면 화면을 누르세요.</p></div>
			<div class="p-box"></div>
			<%= link_to 'Write', new_diary_daily_path, class:"animsition-link blog-link chaffle" %>
	</div>	
 
 
  
  
	<% @dailies.each do |daily| %>	
	<div class="blog-box-1 grey-background quote">
	  	<div class="date"><p><span><%= daily.today.day %>/</span><%= daily.today.month %>.<%= daily.today.year %><em><%= daily.country %></em></p></div>
	      <% if daily.daily_attachments.length != 0 %>
	      <a><%= image_tag (daily.daily_attachments.sample(1)[0].avatar.thumb.url)%></a>
	      <% end %>
	      <div class="card-body">
	        <h5 class="card-title"><%= daily.title %></h5>
	        
	        <%= link_to 'read more', diary_daily_path(@diary, daily), class:"animsition-link blog-link chaffle" %>
	      </div>
	    </div>
    <% end %>

		<!--<div class="blog-box-1 grey-background video">-->
		<!--	<div class="date"><p><span>28/</span>mar.2015. <em>John Doe</em></p></div>-->
		<!--	<figure class="vimeo"> -->
		<!--		<a href="http://player.vimeo.com/video/112766731">-->
		<!--			<img src="<%#=asset_path 'blog/vimeo.jpg' %>" alt="image" />-->
		<!--		</a>-->
		<!--	</figure>		-->
		<!--	<a href="post.html" class="animsition-link"><h5>icy rocky waves</h5></a>-->
		<!--	<div class="p-box"><p>Vivamus dapibus rutrum. Etiam in nulla arcu, ut vehicula velit.</p></div>-->
		<!--	<a href="post.html" class="animsition-link blog-link chaffle" data-lang="en">read more</a>	-->
		<!--</div>-->

	</div>

</div>
<script> 
(function($) { "use strict";          
			jQuery(document).ready(function() {
				var offset = 350;
				var duration = 500;
				jQuery(window).scroll(function() {
					if (jQuery(this).scrollTop() > offset) {
						jQuery('.scroll-to-top').fadeIn(duration);
					} else {
						jQuery('.scroll-to-top').fadeOut(duration);
					}
				});
				
				jQuery('.scroll-to-top').click(function(event) {
					event.preventDefault();
					jQuery('html, body').animate({scrollTop: 0}, duration);
					return false;
				})
			});
})(jQuery);
</script>

<script>
(function($) { "use strict";
	$(document).ready(function() {
	  
	  $(".animsition").animsition({
	  
		inClass               :   'fade-in-right',
		outClass              :   'fade-out-right',
		inDuration            :    600,
		outDuration           :    600,
		linkElement           :   '.animsition-link',
		// e.g. linkElement   :   'a:not([target="_blank"]):not([href^=#])'
		loading               :    true,
		loadingParentElement  :   'body', //animsition wrapper element
		loadingClass          :   'animsition-loading',
		unSupportCss          : [ 'animation-duration',
								  '-webkit-animation-duration',
								  '-o-animation-duration'
								],
		//"unSupportCss" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
		//The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
		
		overlay               :   false,
		
		overlayClass          :   'animsition-overlay-slide',
		overlayParentElement  :   'body'
	  });
	  
	});
})(jQuery);
</script>

<script>
(function($) { "use strict";
	$(document).ready(function() {
	  $('.chaffle').chaffle({
		speed: 10,
		time: 60
	  });
	}); 
})(jQuery);
</script>


<script> 
(function($) { "use strict"; 
	$(".blog-box-1").fitVids();	
})(jQuery);
</script>
<script> 
(function($) { "use strict"; 
	$('.vimeo a,.youtube a').click(function (e) {
		e.preventDefault();
		var videoLink = $(this).attr('href');
		var classeV = $(this).parent();
		var PlaceV = $(this).parent();
		if ($(this).parent().hasClass('youtube')) {
			$(this).parent().wrapAll('<div class="video-wrapper">');
			$(PlaceV).html('<iframe frameborder="0" height="333" src="' + videoLink + '?autoplay=1&showinfo=0" title="YouTube video player" width="547"></iframe>');
		} else {
			$(this).parent().wrapAll('<div class="video-wrapper">');
			$(PlaceV).html('<iframe src="' + videoLink + '?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1&amp;color=16a085" width="500" height="281" frameborder="0"></iframe>');
		}
	});		
})(jQuery);
</script>

<script>
(function($) { "use strict";
	//Tooltip
	
	$(".tipped").tipper();
})(jQuery);
</script>


<%= render 'shared/modal1' %>
<%= render 'shared/modal2' %>
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>

app/views/dailies/new.html.erb
<h1>New Daily</h1>

<%= render 'form', daily: @daily, diary: @diary %>

<%= link_to 'Back', diary_dailies_path %>

app/views/dailies/show.html.erb
<div class="section section-padding-top-bottom-head">
			
				<div class="parallax-project-7"></div>	
				<!-- 제목 -->
				<div class="container">	
					<div class="sixteen columns">
						<div class="section-head-text left">
							<h2><%=@diary.title %></h2>
							<p><%= @daily.title %></p>
						</div>
					</div>	
				</div>
			  </div>
			  <!-- 제목 끝 -->
			  
			  <!-- 사진  -->
			  <div class="section section-padding-top-bottom grey-background">						
  				<div class="container">		
  				  					<div class="col-md-12">		
  						<div class="blog-box-1 post-page">
  							<div class="date"><p><span><%= @daily.today.day %>/</span><%= @daily.today.month %>.<%= @daily.today.year %> <em><%= @daily.country %></em></p></div>
  						</div>	
  					</div>	
  					<div class="col-md-12">				
  						<div id="owl-project-wrapper">
  							<div class="customNavigation">
  								<a class="prev tipped" data-title="prev"  data-tipper-options='{"direction":"top","follow":"true","margin":30}' ></a>
  								<a class="next tipped" data-title="next"  data-tipper-options='{"direction":"top","follow":"true","margin":30}' ></a>
  							</div>
  							<div id="owl-project" class="owl-carousel owl-theme">
  								     <% @daily_attachments.each do |p| %>
  								    	<div class="item">
                        					<%= image_tag p.avatar_url %>
                        					</div>
                        			<% end %>
                      				
  								</div>
  						</div>	
  					</div>

  					
  				</div>	
				</div>
			
			
      <!-- 글 -->
				<div class="section section-padding-top-bottom white-background">						
				<div class="container">	
					<div class="col-md-12" data-scroll-reveal="enter bottom move 100px over 0.6s after 0.3s">
						<div class="project-block"><p><%= @daily.content.html_safe %></p></div>
					</div>
						<br>
              <%= link_to 'Edit', edit_diary_daily_path(@daily), class: "btn clever-btn animated" %> |
              <%= link_to 'Back', diary_dailies_path, class: "btn clever-btn animated" %> |
              <%= link_to 'Destroy', diary_daily_path, class: "btn clever-btn animated ", method: :delete %> 

            </br>
				</div>	
			</div>

</div>

<!-- 댓글 창 고쳐야함 --> 
<div class="blog-replay-wrapper">
  <h4 class="blog-details-title2">HAVE 2 COMMENTS</h4>


<div class="single-blog-replay">
      <div class="replay-info-wrapper">
          <p>
            <!--댓글 New-->
            <%= form_for(@daily_comment, remote: true ) do |f| %>
              <%= f.text_field :content %>
              <%= f.hidden_field :daily_id, value: @daily.id%>
              <%= f.hidden_field :diary_id, value: @diary.id %> 
              <%= f.hidden_field :user_id, value:  current_user.id %> 
              <%= f.submit %>
            <% end %>
           </p>
      </div>
  </div>
</div>
<!-- 끝 -->

<!--댓글 Show-->
<ul id="daily_comments">
  <% @daily_comments.each do |comment| %>
    <%= render 'daily_comments/comment', comment: comment %>
  <% end %>
</ul>


<!-- 이건 테마 -->
<script>
var form = "";
(function($) { "use strict";	
	$(document).ready(function() {
	
	  var time = 7; // time in seconds
	 
	  var $progressBar,
		  $bar, 
		  $elem, 
		  isPause, 
		  tick,
		  percentTime;
	 
		//Init the carousel
		$("#owl-project").owlCarousel({
			pagination : false,
			slideSpeed : 500,
			paginationSpeed : 500,
			singleItem:true,
			afterInit : progressBar,
			afterMove : moved,
			startDragging : pauseOnDragging			
		});

		
		//Init progressBar where elem is $("#owl-demo")
		function progressBar(elem){
		  $elem = elem;
		  //build progress bar elements
		  buildProgressBar();
		  //start counting
		  start();
		}
	 
		//create div#progressBar and div#bar then prepend to $("#owl-demo")
		function buildProgressBar(){
		  $progressBar = $("<div>",{
			id:"progressBar"
		  });
		  $bar = $("<div>",{
			id:"bar"
		  });
		  $progressBar.append($bar).prependTo($elem);
		}
	 
		function start() {
		  //reset timer
		  percentTime = 0;
		  isPause = false;
		  //run interval every 0.01 second
		  tick = setInterval(interval, 10);
		};
	 
		function interval() {
		  if(isPause === false){
			percentTime += 1 / time;
			$bar.css({
			   width: percentTime+"%"
			 });
			//if percentTime is equal or greater than 100
			if(percentTime >= 100){
			  //slide to next item 
			  $elem.trigger('owl.next')
			}
		  }
		}
	 
		//pause while dragging 
		function pauseOnDragging(){
		  isPause = true;
		}
	 
		//moved callback
		function moved(){
		  //clear interval
		  clearTimeout(tick);
		  //start again
		  start();
		}
	 
		//uncomment this to make pause on mouseover 
		// $elem.on('mouseover',function(){
		//   isPause = true;
		// })
		// $elem.on('mouseout',function(){
		//   isPause = false;
		// })
 	 
	  var owl = $("#owl-project");
	 
	  owl.owlCarousel();
	 
	  // Custom Navigation Events
	  $(".next").click(function(){
		owl.trigger('owl.next');
	  })
	  $(".prev").click(function(){
		owl.trigger('owl.prev');
	  })
	 
	});				
})(jQuery);
</script>